openapi: 3.0.0
info:
  title: Task Tracker
  contact: {}
  version: '1.0'
servers:
- url: https://task-tracker-do9u.onrender.com/api/v1
  variables: {}
paths:
  /task-tracker:
    get:
      tags:
      - Task Tracker
      summary: Get All Task
      operationId: GetAllTask
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    post:
      tags:
      - Task Tracker
      summary: Create Task
      operationId: CreateTask
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateTaskRequest'
              - example:
                  title: I am doing Production fake task
                  description: I will go home on 12PM midnight
            example:
              title: I am doing Production fake task
              description: I will go home on 12PM midnight
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /task-tracker/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: The Task Tracker ID
    patch:
      tags:
      - Task Tracker
      summary: Update Task
      operationId: UpdateTask
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateTaskRequest'
              - example:
                  title: Production testing Update
                  description: UI should be clean
                  status: pending
                  proiority: high
            example:
              title: Production testing Update
              description: UI should be clean
              status: pending
              proiority: high
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /task-tracker/{taskid}:
    parameters:
      - in: path
        name: taskid
        schema:
          type: integer
        required: true
        description: The Task Tracker ID
    delete:
      tags:
      - Task Tracker
      summary: Delete Task
      operationId: DeleteTask
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /auth/register:
    post:
      tags:
      - Authentication
      summary: Register User
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/RegisterUserRequest'
              - example:
                  name: John Fedex
                  email: john.production@gmail.com
                  password: password
                  confirmPassword: password
            example:
              name: John Fedex
              email: john.production@gmail.com
              password: password
              confirmPassword: password
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth:
    post:
      tags:
      - Authentication
      summary: Login User
      operationId: LoginUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginUserRequest'
              - example:
                  email: john.fedex@gmail.com
                  password: password
            example:
              email: john.fedex@gmail.com
              password: password
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
      - name
      - email
      - password
      - confirmPassword
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
      example:
        name: John Fedex
        email: john.production@gmail.com
        password: password
        confirmPassword: password
    LoginUserRequest:
      title: LoginUserRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: john.fedex@gmail.com
        password: password
    CreateTaskRequest:
      title: CreateTaskRequest
      required:
      - title
      - description
      type: object
      properties:
        title:
          type: string
        description:
          type: string
      example:
        title: I am doing Production fake task
        description: I will go home on 12PM midnight
    UpdateTaskRequest:
      title: UpdateTaskRequest
      required:
      - title
      - description
      - status
      - proiority
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
        proiority:
          type: string
      example:
        title: Production testing Update
        description: UI should be clean
        status: pending
        proiority: high
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Authentication
  description: ''
- name: Task Tracker
  description: ''
